// IPC channel names shared by main (ipcMain.handle) and preload (ipcRenderer.invoke).
// One channel per QuantApi method — see src/shared/types.ts for signatures.

export const IPC = {
  watchlistGet: 'watchlist:get',
  watchlistAdd: 'watchlist:add',
  watchlistRemove: 'watchlist:remove',
  watchlistReorder: 'watchlist:reorder',
  symbolsSearch: 'symbols:search',
  quotesGet: 'quotes:get',
  holdingsGet: 'holdings:get',
  newsGet: 'news:get',
  earningsGet: 'earnings:get',
  chartGet: 'chart:get',
  pivotNewsGet: 'chart:pivot-news',
  macroOverlayGet: 'chart:macro-overlay',
  chartSnapshotCapture: 'chart:capture-snapshot',
  quantAnalyze: 'quant:analyze',
  quantInsightsGet: 'quant:insights-get',
  quantJournalGet: 'quant:journal-get',
  quantJournalSave: 'quant:journal-save',
  llmSettingsGet: 'llm-settings:get',
  llmSettingsSave: 'llm-settings:save',
  llmConnectionTest: 'llm-settings:test',
  valuationGet: 'valuation:get',
  signalsScan: 'signals:scan',
  forecastRun: 'forecast:run',
  forecastCancel: 'forecast:cancel',
  forecastGetJob: 'forecast:get-job',
  forecastListSaved: 'forecast:list-saved',
  forecastGetSaved: 'forecast:get-saved',
  forecastGetHistoricalComparison: 'forecast:get-historical-comparison',
  forecastSetOverlayEnabled: 'forecast:set-overlay-enabled',
  forecastGetOverlayEnabled: 'forecast:get-overlay-enabled',
  forecastProgress: 'forecast:progress',
  forecastCompleted: 'forecast:completed',
  forecastFailed: 'forecast:failed',
  openExternal: 'shell:open-external',
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
