// Lookup for the measured performance of a strategy, used to put numbers in
// the alert instead of adjectives.
//
// Generated by src/analysis/strategyScoreboard.js. Read-only here on purpose:
// the alert must quote the same table the scoreboard prints, so recomputing at
// send time (on a different sample, at a different moment) would let the
// message and the table drift apart while both looked authoritative.

const fs = require('node:fs');
const path = require('node:path');

let STATS = { _meta: {}, strategies: {} };
try {
  STATS = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'data', 'strategy-stats.json'), 'utf8'));
} catch {
  // Alerts still send without it; they just carry no stats block.
}

// Which row of the scoreboard describes this alert. The rare tier is measured
// under its own name and must not borrow plain cup-forming's much weaker row
// (0.911R vs 0.114R — quoting the wrong one would overstate by 8x).
function statsKeyFor({ kind, rareTier }) {
  return rareTier ? 'RARE (as shipped, scoped)' : kind;
}

// `tier` is 'bigcap' | 'midcap' — the split matters more than the headline,
// because bigcap random entries returned 0.226R over this window and midcap
// returned -0.010R, so the same avgR means very different things in each.
function statsFor({ kind, rareTier = false, capTier = null }) {
  const key = statsKeyFor({ kind, rareTier });
  const row = STATS.strategies?.[key];
  if (!row) return null;
  const scoped = capTier && row[capTier] ? row[capTier] : row.all;
  if (!scoped) return null;
  return {
    key,
    rank: row.rank,
    of: row.of,
    capTier: capTier && row[capTier] ? capTier : 'all',
    n: scoped.n,
    winRate: scoped.winRate,
    avgR: scoped.avgR,
    rr: scoped.rr,
    t: scoped.t,
    beatsRandom: row.beatsRandom,
    randomBaseline: STATS._meta?.randomBaseline
      ? (capTier && STATS._meta.randomBaseline[capTier] !== undefined
        ? STATS._meta.randomBaseline[capTier]
        : STATS._meta.randomBaseline.all)
      : null,
    holdDays: STATS._meta?.holdDays ?? 14,
    costPercent: STATS._meta?.costPercent ?? 0.25,
  };
}

// Expectancy in R is the honest unit (it is leverage-independent), but R is
// abstract at a glance. Converting through the actual stop width gives the
// same number as a move in percent, which is what shows up on a chart.
function expectancyPercent(avgR, stopDistancePercent) {
  if (avgR === null || avgR === undefined || !stopDistancePercent) return null;
  return Math.round(avgR * stopDistancePercent * 100) / 100;
}

module.exports = { statsFor, statsKeyFor, expectancyPercent, STATS };
